name: PR Pipeline - Build, Test, Deploy Gate

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

  test:
    name: ✅ Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  deploy:
    name: 🚀 Deploy (Approval Required)
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: staging
      url: https://studentroutinetrackerapi.onrender.com
    steps:
      - name: Confirm Deployment
        run: echo "✅ Code passed all checks and is ready to deploy."
